default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000
  username: gsm
  
development:
  <<: *default
  database: gsm_development

test:
  <<: *default
  pool: 4
  database: gsm_test



production:
  <<: *default
  pool: 5
  database: gsm_production

